<a href="echo_and_print.php">Echo and print</a><br />
<a href="constants_and_variables.php">Constants and variables</a><br />
<a href="typecasting.php">Typecasting</a><br />
<a href="booleans.php">Booleans</a><br />
<a href="integers.php">Integers</a><br />
<a href="floats.php">Floats</a><br />
<a href="strings.php">Strings</a><br />
<a href="null.php">Null</a><br />
<a href="arrays.php">Arrays</a><br />
<a href="expressions.php">Expressions</a><br />
<a href="operators.php">Operators</a><br />
<a href="operator_precedence_and_associativity.php">Operator precedence and associativity</a><br />
<a href="conditional_statements.php">Conditional statements</a><br />
<a href="loops.php">Loops</a><br />
<a href="switch_statements.php">Swicth statements</a><br />
