<a href="echo_and_print.php">Echo and print</a><br />
<a href="constants_and_variables.php">Constants and variables</a><br />
<a href="typecasting.php">Typecasting</a><br />
<a href="booleans.php">Booleans</a><br />
<a href="integers.php">Integers</a><br />
<a href="floats.php">Floats</a><br />
<a href="strings.php">Strings</a><br />
<a href="null.php">Null</a><br />
<a href="arrays.php">Arrays</a><br />
<a href="expressions.php">Expressions</a><br />
<a href="operators.php">Operators</a><br />
<a href="operator_precedence_and_associativity.php">Operator precedence and associativity</a><br />
<a href="conditional_statements.php">Conditional statements</a><br />
<a href="loops.php">Loops</a><br />
<a href="switch_and_match_statements.php">Switch() and Match() statements</a><br />
<a href="return_declare_and_tickable_statements.php">Return, declare and tickable statements</a><br />
<a href="files_include_and_require.php">Files - include and require</a><br />
<a href="functions.php">Functions</a><br />
<a href="function_parameters_variadic_functions_and_unpacking.php">Function parameters, variadic functions and unpacking</a><br />
<a href="variable_scopes_static_variables.php">Variable scopes, static variables</a><br />
<a href="variable_and_other_function_types.php">Variable, Anonymous, Callable, Closure & Arrow Functions (revisit this)</a><br />
<a href="dates_and_timezones.php">Dates and timezones</a><br />

